# Generated by Django 4.1.3 on 2022-12-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('photo', models.CharField(max_length=100)),
                ('fuel', models.CharField(max_length=15)),
                ('fueled', models.IntegerField()),
                ('probeg', models.IntegerField()),
                ('korobka', models.CharField(max_length=15)),
                ('available', models.BooleanField()),
            ],
        ),
    ]
