# Generated by Django 4.1.3 on 2022-12-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('photo_pass', models.CharField(max_length=100)),
                ('photo_vu', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('staz', models.IntegerField()),
                ('available', models.BooleanField()),
            ],
        ),
    ]
