# Generated by Django 4.1.3 on 2022-12-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='photo_pass',
            field=models.ImageField(upload_to='images_pass'),
        ),
        migrations.AlterField(
            model_name='users',
            name='photo_vu',
            field=models.ImageField(upload_to='images_vu'),
        ),
    ]
