# Generated by Django 4.1.3 on 2022-12-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_users_photo_pass_alter_users_photo_vu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users_Form1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('password2', models.CharField(max_length=100)),
                ('photo_pass', models.ImageField(upload_to='images_pass')),
                ('photo_vu', models.ImageField(upload_to='images_vu')),
            ],
        ),
    ]
