# Generated by Django 4.1.3 on 2022-12-13 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_drives_delete_users_form1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breaks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='breaks')),
                ('status', models.CharField(choices=[('на рассмотрении', 'WAITLIST'), ('зарегистрирована', 'REGISERED'), ('исправлена', 'FIXED'), ('отклонена', 'DECLINED'), ('black', 'BLACK')], max_length=20)),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.drives')),
            ],
        ),
    ]
