# Generated by Django 4.1.3 on 2022-12-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_breaks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price_km', models.FloatField()),
                ('price_minute', models.FloatField()),
                ('time_limit', models.TimeField()),
                ('distance_limit', models.FloatField()),
                ('price', models.FloatField()),
                ('available', models.BooleanField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='auto',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='drives',
            options={'ordering': ['time_start']},
        ),
        migrations.AlterField(
            model_name='breaks',
            name='status',
            field=models.CharField(choices=[('на рассмотрении', 'WAITLIST'), ('зарегистрирована', 'REGISTERED'), ('исправлена', 'FIXED'), ('отклонена', 'DECLINED')], max_length=20),
        ),
    ]
