# Generated by Django 4.1.3 on 2022-12-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_tarify_alter_auto_options_alter_drives_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarify',
            name='time_limit',
            field=models.FloatField(),
        ),
    ]
